packages:
  - apps/*
  - configs/*
  - docs
  - packages/*

catalog:
  eslint: ^9.39.4
  tsdown: ^0.21.7
  tsx: ^4.21.0
  typescript: ^6.0.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
